### ISSUE TITLE
base url in glossary objects may be permanently overwritten

### ISSUE THREAD

**Issue by dechoma** [verdan/pyatlasclient#9]
```
data = {
    "qualifiedName": "DummyGlossary",
    "name": "DummyGlossary",
    "shortDescription": "Short Description of Glossary 'DummyGlossary'",
    "longDescription": "Long Description of Glossary 'DummyGlossary",
}

try:
    terms = driver.glossary.fetch_terms(glossary_guid='nonexistingguid')
except:
    pass
glossary_entity = driver.glossary.create(**data)
```
method driver.glossary.fetch_terms changes  permanently url and this lead to 500 error
HTTP request failed for POST http://localhost:21000/api/atlas/v2/glossary/nonexistingguid/terms: Internal Server Error 500:

```
Traceback (most recent call last):
  File "/Users/dominik/projects/ing/atlas_defs/test.py", line 18, in <module>
    glossary_entity = driver.glossary.create(**data)
  File "/Users/dominik/projects/ing/atlas_defs/venv/lib/python3.8/site-packages/atlasclient/base.py", line 303, in create
    model.create(**kwargs)
  File "/Users/dominik/projects/ing/atlas_defs/venv/lib/python3.8/site-packages/atlasclient/events.py", line 28, in replacement
    return method(self, *args, **kwargs)
  File "/Users/dominik/projects/ing/atlas_defs/venv/lib/python3.8/site-packages/atlasclient/base.py", line 716, in create
    self.load(self.client.post(self.url, data=data))
  File "/Users/dominik/projects/ing/atlas_defs/venv/lib/python3.8/site-packages/atlasclient/client.py", line 170, in request
    handle_response(response)
  File "/Users/dominik/projects/ing/atlas_defs/venv/lib/python3.8/site-packages/atlasclient/exceptions.py", line 210, in handle_response
    raise cls(**kwargs)
atlasclient.exceptions.ServerError: HTTP request failed for POST http://localhost:21000/api/atlas/v2/glossary/nonexistingguid/terms: Internal Server Error 500: There was an error processing your request. It has been logged (ID 9e9b5150143d521a).
```

**Comment by verdan** [comment]
@dechoma can you please explain a bit more? I don't get it what is wrong?

**Comment by dechoma** [comment]
@verdan  the issue here is that method `driver.glossary.create` is using url from previous command (`driver.glossary.fetch_terms`) to create glossary entity , so it POSTs create glossary payload  into glossary terms endpoint  which causes atlas 500 error
